### ISSUE TITLE
Property commands do not respect beep setting

### ISSUE THREAD

**Issue by mill1000** [mill1000/midea-msmart#119]
> Beep is turned off, but the swing positions beep when selecting other options don't.

_Originally posted by @parautenbach in https://github.com/mill1000/midea-ac-py/issues/109#issuecomment-2049403385_

It appears the property commands are not respecting the beep setting.

**Comment by mill1000** [comment]
@parautenbach @v1k70rk4

I've got a potential fix for the beep when changing swing angle. You'll need to run this command within your HA environment (generally within the Docker container)

```
pip install git+https://github.com/mill1000/midea-msmart.git@issue/properties_buzzer
```

**Comment by mill1000** [comment]
Thanks for testing. Try checking your logs to see if the new version of msmart-ng was installed.

On HAOS, HA is still running within a docker container. The above command must be run from within the container.

**Comment by v1k70rk4** [comment]
In theory, I have logged in with this:
`docker exec -it homeassistant /bin/bash`

And I got this after the script:
```
homeassistant:/config# msmart-ng -v
msmart version: 2024.3.3.dev1+ge9a72cf
```

**Comment by mill1000** [comment]
Ok it looks like it took. Does the home-assistant.log report the same version?

**Comment by mill1000** [comment]
Well that's excellent news! I'll get the PR merged and a new version out soon.

**Comment by parautenbach** [comment]
I can confirm that my beeps in this case are gone. :-) Thanks!

(PS: I've spent some time on my back, so I wasn't able to do much to help, unfortunately.)

**Comment by mill1000** [comment]
Thanks for confirming. Hope you are feeling better.
