### ISSUE TITLE
Support power usage and consumption messages

### ISSUE THREAD

**Issue by mill1000** [mill1000/midea-msmart#12]
Originally reported in mill1000/midea-ac-py#5

Some units can report energy usage and total consumption. 

There is support for this in dudanov/MideaUART for [example](https://github.com/dudanov/MideaUART/blob/3bbd505ee58792a620ad115f9f26652b688f58e3/include/Appliance/AirConditioner/StatusData.h#L147-L152)

**Comment by mill1000** [comment]
I've got a PR for this feature, but lack devices to test it. Any volunteers willing to test?

**Comment by Eskander** [comment]
Hi, my AC supports power usage. How do I go about testing this?

**Comment by mill1000** [comment]
Hi. I just posted some instructions in the related PR https://github.com/mill1000/midea-msmart/pull/116#issuecomment-2179435543
