### ISSUE TITLE
firewall is preventing discovery

### ISSUE THREAD

**Issue by ebeighe** [mill1000/midea-msmart#129]
I ran msmart-ng discover on my "test" system, and it was able to locate my window ac just fine.
When i tried it on my "production" system, which is on the same LAN, it fails:
```
INFO:msmart.cli:Discovering all devices on local network.
ERROR:msmart.cli:No devices found.
```
with that 2nd line coming up after a couple of seconds delay.
eventually, it dawned on me, the test system doesn't have any firewall. Disabling the firewall allows it to work as expected.

My question is what rule does it need in the firewall to work as expected?

**Comment by mill1000** [comment]
Hi there. Discovery works via UDP broadcast on ports 6445 and 20086.
