### ISSUE TITLE
capabilities question

### ISSUE THREAD

**Issue by LaptopDev** [mill1000/midea-msmart#130]
From within Home Assistant I only see 
![image](https://github.com/mill1000/midea-msmart/assets/6458102/2630f2cf-ea1d-4c30-87e0-bb37b2c02dea)

When I run the query command:
```
INFO:msmart.cli:Querying device capabilities.
INFO:msmart.cli:{'supported_modes': [<OperationalMode.FAN_ONLY: 5>, <OperationalMode.DRY: 3>, <OperationalMode.COOL: 2>, <OperationalMode.AUTO: 1>], 'supported_swing_modes': [<SwingMode.OFF: 0>, <SwingMode.VERTICAL: 12>], 'supported_fan_speeds': [<FanSpeed.SILENT: 20>, <FanSpeed.LOW: 40>, <FanSpeed.MEDIUM: 60>, <FanSpeed.HIGH: 80>, <FanSpeed.AUTO: 102>], 'supports_custom_fan_speed': True, 'supports_eco_mode': True, 'supports_turbo_mode': True, 'supports_freeze_protection_mode': False, 'supports_display_control': True, 'supports_filter_reminder': True, 'max_target_temperature': 30.0, 'min_target_temperature': 16.0}
```
... It shows max target temperature and min target temperatures but I am unsure if these are technically capabilities. 

I discovered actions for changing the ac temperature setting were missing when configuring a home assistant automation for scheduling ac temperature change events on a time schedule. How can I pull this off considering the capabilities of my unit in the query, and the limited actions visibly available from within a home assistant automation configuration?

I would appreciate any advice

**Comment by mill1000** [comment]
When configuring a HA automation action you need to select the Climate category to set the target temperature. If you select the Device category you'll get a different subset of controls.

No idea why HA has them organized like that.

**Comment by LaptopDev** [comment]
thanks! I clicked `Add Action` button on the automation page and selected the Climate category and now can set the temperature of my unit now
