### ISSUE TITLE
ModuleNotFoundError: No module named 'msmart.cli'

### ISSUE THREAD

**Issue by sakos** [mill1000/midea-msmart#133]
Hello,

I would like to get configuration variables for two Midea ACs. Did not manage with msmart midea-discover (tool works but fail to login to cloud), then I tried with msmart-ng. However, I have a fatal issue with this.

xxx% msmart-ng --help             
Traceback (most recent call last):
  File "/Users/ekosszo/Library/Python/3.9/bin/msmart-ng", line 5, in <module>
    from msmart.cli import main
ModuleNotFoundError: No module named 'msmart.cli'

I am not an expert. Probably something essential is missing on my computer.

**Comment by mill1000** [comment]
Make sure you've uninstalled the original msmart before installing the new version.

You may need to uninstall both and re-install to get a clean install.
```
pip uninstall msmart msmart-ng
pip install msmart-ng
```

**Comment by sakos** [comment]
Thanks, it helped.
It is a bit odd that one device is found online the other is not. I will retry...
