### ISSUE TITLE
Using NetHome Plus (com.midea.aircondition), but not supported

### ISSUE THREAD

**Issue by udiNur** [mill1000/midea-msmart#143]
After encountering issues with the usage of https://github.com/mac-zhou/midea-ac-py, I proceeded to install the msmart-ng package via pip. Upon running the scan command, I received the following output:

```
{'ip': 'xxxxxxx', 'port': 6444, 'id': 150633093832xxx, 'online': False, 'supported': False, 'type': <DeviceType.AIR_CONDITIONER: 172>, 'name': 'net_ac_095C', 'sn': '000000P0000000Q12459E542xxxx0000', 'key': None, 'token': None}
```

I have observed that the 'supported' field is False. Could you kindly advise on any additional information that I could provide to address this issue? Thank you.

**Comment by udiNur** [comment]
Due to my accidental omission, I failed to provide the app account and password which resulted in the inability to obtain device information, as indicated by the "Failed to login to cloud" error.
Now I've getting the expected response!

**Comment by mill1000** [comment]
Cool. Glad it's working.
