### ISSUE TITLE
ERROR:msmart.cli:Device is not online. <<< but device is online

### ISSUE THREAD

**Issue by ETGermany** [mill1000/midea-msmart#160]
Hi, I am just starting to integrate my air conditioning systems into ioBroker, for this I would like to use the commands via CLI (2024.8.0); embedded in Javascript. Two devices are from 2016 and one from 2019. The query of the capabilities does not work with the older devices. Allegedly not online, although commands are executed, such as the fan speed. I would now argue that there is a misinterpretation in the programme here. Attached are the calls for an older and a newer device. Any ideas?

[DIRECT_CMDs.txt](https://github.com/user-attachments/files/16574015/DIRECT_CMDs.txt)

**Comment by ETGermany** [comment]
Perhaps one more question: What about the "SWING DIRECT" command from the remote control - that is probably not supported?

**Comment by mill1000** [comment]
> The query of the capabilities does not work with the older devices. Allegedly not online, although commands are executed, such as the fan speed.

In that case just remove the `--capabilites` argument. You'll still be able to control and query the state.

**Comment by mill1000** [comment]
I'm not familiar with "swing direct" so it's not currently supported. Do you know what the OEM app calls it?

**Comment by ETGermany** [comment]
By querying the capabilities, I only wanted to know which commands are supported by the device. Because swing mode and swing angle, do not work. But why does the program think that the device is offline? Can this be fixed in the program? 

"SWING DIRECT" means that the air outlet can be changed in steps. Is not available in the Midea app, only on the remote control.

**Comment by mill1000** [comment]
> By querying the capabilities, I only wanted to know which commands are supported by the device. ... But why does the program think that the device is offline?

There's nothing to be fixed. 

As we know, your device doesn't support/respond to capabilities requests. The program doesn't get a response to the message so it declares the device offline.

> "SWING DIRECT" means that the air outlet can be changed in steps. Is not available in the Midea app, only on the remote control. 


If it's only available on the remote then generally it's not something msmart-ng will be able to control.

**Comment by ETGermany** [comment]
OK, not pretty, but I have to be happy with it. In conclusion, this should be due to the device, which means the case can be closed.
