### ISSUE TITLE
Followup question to LED display

### ISSUE THREAD

**Issue by apella12** [mill1000/midea-msmart#168]
In reviewing this repository, I see that you recently changed (July 24 PR) the LED display, dropping the Set command from the original author.    I'm going to need to find a tester, since my device doesn't support display_on, but could I trouble you with two quick ones?  Questions: 1) I see the method is labeled "toggle" does that mean each time it is sent it changes from the previous? (No ON or OFF byte to change) 2) Also does sending this query (in devices that support it) change any bit in the 0xC0 response?  Thanks for your consideration Edit: one more ;-), The program I'm working on was started (as is working with Request =0x20, not 0x21.  Any comment on why?

**Comment by mill1000** [comment]
> In reviewing this repository, I see that you recently changed (July 24 PR) the LED display, dropping the Set command from the original author. 

I'm not sure which PR you are referring too. I haven't changed the display control code in some time.

> Questions: 1) I see the method is labeled "toggle" does that mean each time it is sent it changes from the previous? (No ON or OFF byte to change) 

Correct. There is only a toggle command. I have not found a command that can explicitly send ON or OFF.


> 2) Also does sending this query (in devices that support it) change any bit in the 0xC0 response? 

Yes there is a field for `display_on` in the state response 
https://github.com/mill1000/midea-msmart/blob/e614ee5d80ab840d27ec1bef07525a5e305d6eb3/msmart/device/AC/command.py#L859

> The program I'm working on was started (as is working with Request =0x20, not 0x21. Any comment on why?

Sorry, I'm not sure I understand the question.

**Comment by apella12** [comment]
Maybe the July PR was on the HA repository.  Anyway no matter
Thanks for 1) and 2)
As to the last, the first three bytes of a query in the program I'm working on are `0xaa 0x20 0xac`, not `0xaa 0x21 0xac` Not critical just curious if you know any history?

**Comment by mill1000** [comment]
That's the length byte.

**Comment by apella12** [comment]
That is incredibly enlightening.  Thanks The java doc in the program implied that "20" for for query and "23" was for set. Now I understand why they added three 0x00 bytes.  Anyway, I'll get out of your hair.

You are way ahead of my effort, but I noticed the timers were commented out.  I found the minutes (at least on my device) were handled differently than in the original sources.  You probably already know that but just in case, try
`minutes = ((data[0x04] & 0x3) * 15 + 15 - (((data[0x06] & (byte) 0xf0) >> 4) & 0x0f));` On timer.

Thanks for the insight.

**Comment by mill1000** [comment]
> You are way ahead of my effort, but I noticed the timers were commented out. I found the minutes (at least on my device) were handled differently than in the original sources. You probably already know that but just in case, try
> `minutes = ((data[0x04] & 0x3) * 15 + 15 - (((data[0x06] & (byte) 0xf0) >> 4) & 0x0f));` On timer.

I've never actually tested or used the timer code so it's very possible it's buggy.  

Since the main target of this library was for integration with home automation systems I felt supporting the timers was an unnecessary feature that could be handled better by the automation system.


Anway, good luck! Feel free to ask for help.
