### ISSUE TITLE
ECO mode is not activating

### ISSUE THREAD

**Issue by paradox37** [mill1000/midea-msmart#3]
Hello,

First thanks for great work in your future branch. I have Vivax AC which is just rebranded Midea AC. It supports ECO and Freeze protection but I can not get any to work with Home Assistant integration. I used your future branch. When I activate ECO preset, it just returns to None. Regarding Freeze protection, I can not see it anywhere in Entites to even try it. According to logs, AC supports ECO and freeze protection, and it works when I use NetHome app, but not with this or any other integration I tried.

Here is the relevant part of the log:

```
2022-11-13 20:26:45.104 DEBUG (SyncWorker_6) [msmart.device.AC.command] Capabilities response payload: b5071202010113020101140201011502010116020101170201001a020101
2022-11-13 20:26:45.105 DEBUG (SyncWorker_6) [msmart.device.AC.command] Supported capabilities: {'eco_mode': True, 'eco_mode_2': False, 'freeze_protection': True, 'heat_mode': True, 'cool_mode': False, 'dry_mode': True, 'auto_mode': True, 'swing_horizontal': True, 'swing_vertical': True, 'power_cal': False, 'power_cal_setting': False, 'nest_check': False, 'nest_need_change': False, 'turbo_heat': True, 'turbo_cool': True}
```

Any way you can help? I am willing to work with you and provide any info you need.

**Comment by mill1000** [comment]
Hey, sorry I missed this issue as (somehow) I wasn't notified of issues in my own repo.

Make sure you're running the future branch of mill1000/midea-ac-py as well. 

When you activate ECO mode in HA, does the unit switch to over to ECO (even if briefly)?

Freeze protection is implemented as an additional operation mode. I think it's titled "Away Mode".

**Comment by mill1000** [comment]
Ok good to know that FP is working at least.

I wonder if there's different handling required for eco_mode vs eco_mode2.

If you enable ECO mode via the NetHome, does HA show that the device has entered ECO mode? 

Can you supply `State response payload:` log messages with ECO mode enabled and disabled? We might need to set & check a different bit.

**Comment by paradox37** [comment]
Can't believe it. ECO mode is only for cooling. When I tried to activate it in NetHome, it said can not be used in current mode. That's why it can not be activated in HA also. When I switched to cooling, it also worked in HA. That's great. 

For the heating, I have Sleep Curve in Net Home, which saves energy during night. Do you think that's something you could add?

What would I need to provide for that?

**Comment by mill1000** [comment]
> Can't believe it. ECO mode is only for cooling, not for heating. When I tried to activate it in NetHome, it said can not be used in current mode. That's why it can not be activated in HA also. When I switched to cooling, it also worked in HA. That's great.

Good to know. Could you make an issue at for that at  mill1000/midea-ac-py? I'll update the integration to only show the ECO preset when in cooling mode.

> For the heating, I have Sleep Curve in Net Home, which saves energy during night. Do you think that's something you could add?

Does this sleep curve work like a preset? e.g. is it similar to Freeze Protection and ECO?

Looks like the code is already has the bits for a sleep mode so it might just be a matter of exposing them to HA.
https://github.com/mill1000/midea-msmart/blob/0c475f1a0e27fd6a050ca14e0b018635edd9eb20/msmart/device/AC/command.py#L151-L152

**Comment by paradox37** [comment]
> Could you make an issue at for that at mill1000/midea-ac-py? I'll update the integration to only show the ECO preset when in cooling mode.

Done.

> Does this sleep curve work like a preset? e.g. is it similar to Freeze Protection and ECO?

I believe it works like a preset. On the remote I have a button for it to toggle the operation. Here is the explanation from manual:

> When you press the SLEEP button, the
> economic running function will be activated.
> During Cooling, Heating or AUTO operation,
> the set temperature of the air conditioner
> will automatically increase or decrease 1 C
> per hour for 2 hours. After 2 hours, the set
> point will continue at that temperature and
> the fan motor will be set to LOW speed.
> The sleep mode function can maintain the
> most comfortable temperature and save
> more energy for you.
> NOTE: The SLEEP function is only available
> under Cooling, Heating and AUTO
> operation.

**Comment by mill1000** [comment]
Sounds like a preset to me. Also sound some references to it in [dudanov](https://github.com/dudanov) /
[MideaUART](https://github.com/dudanov/MideaUART)

https://github.com/dudanov/MideaUART/blob/311f992b996fb299204b7e9857ff1fba17338775/src/Appliance/AirConditioner/AirConditioner.cpp#L22-L39

**Comment by paradox37** [comment]
Great. Do you think you could expose this preset so I can test it ?

**Comment by mill1000** [comment]
I'll see if I can get around to is this week

**Comment by mill1000** [comment]
Here are some branches to test sleep mode if you'd be so kind..

You'll need to install an updated msmart in your HA environment (e.g. the container)
pip install git+https://github.com/mill1000/midea-msmart.git@feature/sleep_mode

And then manually install this branch of midea-ac-py
midea-ac-py feature/sleep_preset
https://github.com/mill1000/midea-ac-py/tree/feature/sleep_preset

**Comment by paradox37** [comment]
Sure. But I am not sure how to update msmart. Can you help? I am running home assistant on NUC inside VMware Player, I was lazy to install it directly on NUC. And pip command in terminal is not available for some reason. I tried to change branch in the manifest and reboot Home Assistant, but I am not sure if that did the trick.

**Comment by mill1000** [comment]
You need to run the pip command inside whatever environment HA is running in. If it's HomeAssistant OS you can use this add-on (https://github.com/hassio-addons/addon-ssh). You need to make sure its within the docker container too.

`pip install git+https://github.com/mill1000/midea-msmart.git@feature/sleep_mode`

**Comment by paradox37** [comment]
Okay, I managed to install it. This Sleep mode does something, AC beeps and it preset stays active, fan speed is reduced, but in NetHome, Sleep curve is not activated, so, I can not say with certainty what this preset does to the AC.

**Comment by paradox37** [comment]
Disregard my previous comment. This works as intended, NetHome shows again as crap. When I activated Sleep via AC remote, it changed in the Home Assistant to the Sleep preset. Thank you!

**Comment by mill1000** [comment]
Thanks for testing.
