### ISSUE TITLE
Freeze protection mode capability is not recognized

### ISSUE THREAD

**Issue by trvboro** [mill1000/midea-msmart#76]
I have Midea Mission Pro 9, which is a model of Midea's AC imported and sold by Finnish distributor Onninen. Midea-msmart (version 2023.9.5) is unable to recognize the capability of freeze protection mode, and a warning about unknown capability is output:

> msmart-ng query --token [hidden] --key [hidden]--capabilities 10.0.0.123
> INFO:msmart.lan:Creating new connection to 10.0.0.123:6444.
> INFO:msmart.lan:Authenticating with 10.0.0.123:6444.
> INFO:msmart.lan:Authentication successful. Expiration: 2023-09-21T06:18:05, Local key: [hidden]
> INFO:msmart.cli:Querying device capabilities.
> **WARNING:msmart.device.AC.command:Unknown capability. ID: 0x  40, Size: 1.**
> INFO:msmart.cli:{'supported_modes': [<OperationalMode.FAN_ONLY: 5>, <OperationalMode.DRY: 3>, <OperationalMode.COOL: 2>, <OperationalMode.HEAT: 4>, <OperationalMode.AUTO: 1>], 'supported_swing_modes': [<SwingMode.OFF: 0>, <SwingMode.HORIZONTAL: 3>, <SwingMode.VERTICAL: 12>, <SwingMode.BOTH: 15>], 'supports_eco_mode': True, 'supports_turbo_mode': True, **'supports_freeze_protection_mode': False**, 'supports_display_control': False, 'max_target_temperature': 30.0, 'min_target_temperature': 16.0}

Nevertheless querying the device is still able to tell whether the freeze protection mode is enabled or disabled:

> msmart-ng query --token [hidden] --key [hidden] 10.0.0.123
> INFO:msmart.lan:Creating new connection to 10.0.0.123:6444.
> INFO:msmart.lan:Authenticating with 10.0.0.123:6444.
> INFO:msmart.lan:Authentication successful. Expiration: 2023-09-21T06:19:44, Local key: [hidden]
> INFO:msmart.cli:Querying device state.
> INFO:msmart.cli:{'ip': '10.0.0.123', 'port': 6444, 'id': 0, 'online': True, 'supported': True, 'type': <DeviceType.AIR_CONDITIONER: 172>, 'name': None, 'sn': None, 'key': '[hidden]', 'token': '[hidden]', 'power': True, 'mode': <OperationalMode.HEAT: 4>, 'fan_speed': <FanSpeed.AUTO: 102>, 'swing_mode': <SwingMode.VERTICAL: 12>, 'target_temperature': 17.0, 'indoor_temperature': 17.0, 'outdoor_temperature': 13.0, 'eco': False, 'turbo': False, **'freeze_protection': True**, 'sleep': False, 'display_on': True, 'beep': False, 'fahrenheit': False}

Note. The query is reporting incorrect target temperature. The actual target temp on the device is 16 degrees, not 17. I created an issue about that on midea-ac-py, but it might actually be a bug of midea-msmart.

**Comment by mill1000** [comment]
Hi, can you rerun both commands with the debug option: `-d`? 

> WARNING:msmart.device.AC.command:Unknown capability. ID: 0x 40, Size: 1.
I've seen this before in a few other logs. I have yet to find any documentation on that this capability is.

**Comment by mill1000** [comment]
Can you also provided the protocol file? You can fetch it with `msmart-ng download 10.0.0.123`.

 It might shed some clues on your specific device.

**Comment by mill1000** [comment]
Thanks. It might just be that the device capabilities are reported incorrectly. (Maybe that's why there's a stray 0x0040 capability that's not documented?)

Does the OEM app show freeze protection as available on your device?

The midea-ac-py integration has a workaround for this. There's a configuration option to show all presets regardless or capabilities
![image](https://github.com/mill1000/midea-msmart/assets/6924622/aa683a8b-8796-4b5d-9bca-50330dd08771)

**Comment by pauliborodulin** [comment]
OEM app shows FP (freeze protection) available and I use it regularly. And yes, Show All Presets can be used as a workaround.

**Comment by mill1000** [comment]
Ok. For now I'm going to close issue as a quirk of the particular device. If you feel otherwise, feel free to reopen

**Comment by mill1000** [comment]
FYI this issue was probably a result of not processing the full capabilities from the device (#98), which has been fixed in [2023.12.0](https://github.com/mill1000/midea-msmart/releases/tag/2023.12.0)
