### ISSUE TITLE
High fan speed should have a value of 80

### ISSUE THREAD

**Issue by mill1000** [mill1000/midea-msmart#95]
> Alright thanks! So what's happening is your device uses 80 for high speed, which I removed in this commit https://github.com/mill1000/midea-msmart/commit/d839872233320fca0d8fee15fa0bd60b081b51f7

But upon reviewing some of the reference code it looks like 80 is the correct value for "high", and 100 is for "strong".

From the Lua:
https://github.com/mill1000/midea-msmart/blob/210d02ef551345c43ca2e40873a9d6080c1297b8/reference/T_0000_AC_00000Q1B_2023072401.lua#L241

From the plugin
```js
if (windSpeed === "Mute") {
    return 20;
} else if (windSpeed === "Low") {
    return 40;
} else if (windSpeed === "Mid") {
    return 60;
} else if (windSpeed === "High") {
    return 80;
} else if (windSpeed === "Strong") {
    return 100;
} else if (windSpeed === "Auto") {
    return 102;
} else {
    return 102;
}
```

_Originally posted by @mill1000 in https://github.com/mill1000/midea-msmart/issues/88#issuecomment-1791905935_

**Comment by tabascoz** [comment]
Thanks ! I tested and it works as expected with high as 80, looks my device doesn't support 100 

Cheers, Fernando

**Comment by mill1000** [comment]
Thanks for confirming. 

This is a trivial change to make, I'm just hesitant because my devices are away for the year and I am unable to test if there are unexpected side effects
