### ISSUE TITLE
Control Support for CLI

### ISSUE THREAD

**Issue by MarcelMertens** [mill1000/midea-msmart#96]
Hi,
any chance to add control support for the CLI tool?
Currently only discover and query is possible but not control the device via CLI.

Kind Regards

**Comment by mill1000** [comment]
I've put a little thought into this. The primary problem to solve it how to get the desired control inputs from the command line. 

I think having options for every possible control would be difficult to maintain so I'm leaning towards parsing a string of key-value pairs. 

The syntax could be a simple custom format of `key=value`
e.g.
```
msmart-ng control <DEVICE_IP> power=True fan_speed=100 target_temperature=25
```

Or the format could be a more complex but readily parsable format via [literal_eval](https://docs.python.org/3/library/ast.html#ast.literal_eval) or maybe JSON
```
msmart-ng control <DEVICE_IP> {'power' : True, 'fan_speed' : 100, 'target_temperature' : 25}
```

**Comment by MarcelMertens** [comment]
thank you for your feedback.
in the meanwhile i build my own FastAPI server based on you libraries.

**Comment by niklas85** [comment]
Is there any progress for the device control by cli commands?

**Comment by mill1000** [comment]
Unfortunately no. I have not dedicated any time to this. I always welcome PRs though.

At this time I think the cleanest UX would be to support `key=value` pairs on the command line.

**Comment by mill1000** [comment]
Just pushed a PR #132 to implement this. Still hammering out some of the quirks but it should be usable.
